name: dio_extension
description: .
version: 2.1.0
homepage: https://github.com/hsul4n/dart-extensions/packages/dio

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.2.1+1

dev_dependencies:
  test: ^1.5.1
