name: connectivity_extension
description: .
version: 2.0.0
homepage: https://github.com/hsul4n/dart-extensions/packages/connectivity

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  connectivity_plus: ^4.0.1

dev_dependencies:
  test: ^1.5.1
